### --- Test Setup --- ###

if(TRUE) {
	## Not really needed, but can be handy 
	## when writing tests 
	library("RUnit")
	library("finmix")
}

".setUp.y" <- function() 
{
    ## Get path ##
    pkg <- "finmix"
    if (Sys.getenv("RCMDCHECK") == FALSE) {
        data.path <- file.path(getwd(), "..", 
                               "data", "poisson.data.csv")        
    } else {
        data.path <- system.file(package = pkg, 
                                 'data/poisson.data.csv')
    }
    read.csv(data.path, header = FALSE, sep = ",")
}

".setUp.S" <- function() 
{
    if (Sys.getenv("RCMDCHECK") == FALSE) {
        ind.path <- file.path(getwd(), "..", 
                              "data", 
                              "poisson.ind.csv")        
    } else {
        ind.path <- system.file(package = pkg, 
                                'data/poisson.ind.csv')
    }               
    read.csv(ind.path, header = FALSE, sep = ",")
}

## Testing 
"test.mixturemcmc.poisson.fix" <- function()
{
    ## Setup
    y   <- .setUp.y()
    S   <- .setUp.S()
    fdata.obj   <- fdata(y = y, S = S$V1)
    model.obj   <- model(K = 2, indicfix = TRUE)
    ## Set hier = FALSE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj, 
                               varargin = prior.obj)
    ## Set storepost = FALSE
    mcmc.obj    <- mcmc(storepost = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputfix", "check1")
    checkTrue(!mcmcout@ranperm, "check2")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    ## Set hier = TRUE 
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputfixhier", "check3")
    checkTrue(!mcmcout@ranperm, "check4")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    ## Set hier = FALSE and stroepost = TRUE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj, 
                               varargin = prior.obj)
    mcmc.obj@storepost  <- TRUE
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputfixpost", "check5")
    checkTrue(!mcmcout@ranperm, "check6")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    ## Set hier = TRUE and storepost = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputfixhierpost", "check7")
    checkTrue(!mcmcout@ranperm, "check8")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
}

"test.mixturemcmc.poisson.ind" <- function()
{
    ## Setup
    y   <- .setUp.y()
    S   <- .setUp.S()
    fdata.obj   <- fdata(y = y, S = S$V1)
    model.obj   <- model(K = 2)
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = FALSE, ranperm = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputbase", "check1")
    checkTrue(!mcmcout@ranperm, "check2")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    ## Set hier = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhier", "check3")
    checkTrue(!mcmcout@ranperm, "check4")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    ## Set hier = FALSE and storepost = TRUE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = TRUE, ranperm = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputpost", "check5")
    checkTrue(!mcmcout@ranperm, "check6")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    ## Set hier = TRUE and storepost = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhierpost", "check7")
    checkTrue(!mcmcout@ranperm, "check8")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)  
}

"test.mixturemcmc.poisson.ind.startpar" <- function()
{
    ## Setup
    y   <- .setUp.y()
    S   <- .setUp.S()
    fdata.obj   <- fdata(y = y, S = S$V1)
    model.obj   <- model(K = 2)
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = FALSE, ranperm = TRUE, 
                        startpar = FALSE)
    ## Generate starting parameters 
    (fdata.obj~model.obj~mcmc.obj) %=% mcmcstart(fdata.obj,
                                                 model.obj,
                                                 mcmc.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputbase", "check1")
    checkTrue(mcmcout@ranperm, "check2")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    ## Set hier = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhier", "check3")
    checkTrue(mcmcout@ranperm, "check4")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    ## Set hier = FALSE and storepost = TRUE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = TRUE, ranperm = TRUE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputpost", "check5")
    checkTrue(mcmcout@ranperm, "check6")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    ## Set hier = TRUE and storepost = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhierpost", "check7")
    checkTrue(mcmcout@ranperm, "check8")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)  
}

"test.mixturemcmc.poisson.ind.startpar.ranperm" <- function()
{
    ## Setup
    y   <- .setUp.y()
    S   <- .setUp.S()
    fdata.obj   <- fdata(y = y, S = S$V1)
    model.obj   <- model(K = 2)
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = FALSE, ranperm  = TRUE, 
                        startpar = FALSE)
    ## Generate starting parameters 
    (fdata.obj~model.obj~mcmc.obj) %=% mcmcstart(fdata.obj,
                                                 model.obj,
                                                 mcmc.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputbase", "check1")
    print(mcmcout@ranperm)
    checkTrue(mcmcout@ranperm, "check2")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    ## Set hier = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhier", "check3")
    checkTrue(mcmcout@ranperm, "check4")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    ## Set hier = FALSE and storepost = TRUE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = TRUE, ranperm = TRUE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputpost", "check5")
    checkTrue(mcmcout@ranperm, "check6")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    ## Set hier = TRUE and storepost = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhierpost", "check7")
    checkTrue(mcmcout@ranperm, "check8")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)  
}

## Test special case K = 1
"test.mixturemcmc.poisson.one" <- function()
{
    ## Setup
    y   <- .setUp.y()
    S   <- .setUp.S()
    fdata.obj   <- fdata(y = y, S = S$V1)
    model.obj   <- model(K = 1)
    ## Set hier = FALSE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj, 
                               varargin = prior.obj)
    ## Set storepost = FALSE
    mcmc.obj    <- mcmc(storepost = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputfix", "check1")
    checkTrue(!mcmcout@ranperm, "check2")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    ## Set hier = TRUE 
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputfixhier", "check3")
    checkTrue(!mcmcout@ranperm, "check4")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    ## Set hier = FALSE and stroepost = TRUE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj, 
                               varargin = prior.obj)
    mcmc.obj@storepost  <- TRUE
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputfixpost", "check5")
    checkTrue(!mcmcout@ranperm, "check6")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    ## Set hier = TRUE and storepost = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputfixhierpost", "check7")
    checkTrue(!mcmcout@ranperm, "check8")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
}

"test.mixturemcmc.poisson.ind.byrow" <- function()
{
    ## Setup
    y   <- .setUp.y()
    S   <- .setUp.S()
    fdata.obj   <- fdata(y = t(y), S = t(S$V1))
    model.obj   <- model(K = 2)
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = FALSE, ranperm = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputbase", "check1")
    checkTrue(!mcmcout@ranperm, "check2")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    ## Set hier = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhier", "check3")
    checkTrue(!mcmcout@ranperm, "check4")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    ## Set hier = FALSE and storepost = TRUE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = TRUE, ranperm = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputpost", "check5")
    checkTrue(!mcmcout@ranperm, "check6")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    ## Set hier = TRUE and storepost = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhierpost", "check7")
    checkTrue(!mcmcout@ranperm, "check8")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)  
}
"test.mixturemcmc.poisson.ind" <- function()
{
    ## Setup
    y   <- .setUp.y()
    S   <- .setUp.S()
    fdata.obj   <- fdata(y = y, S = S$V1)
    model.obj   <- model(K = 2)
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = FALSE, ranperm = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputbase", "check1")
    checkTrue(!mcmcout@ranperm, "check2")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    ## Set hier = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhier", "check3")
    checkTrue(!mcmcout@ranperm, "check4")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    ## Set hier = FALSE and storepost = TRUE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = TRUE, ranperm = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputpost", "check5")
    checkTrue(!mcmcout@ranperm, "check6")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    ## Set hier = TRUE and storepost = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhierpost", "check7")
    checkTrue(!mcmcout@ranperm, "check8")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)  
}

"test.mixturemcmc.poisson.ind.expos" <- function()
{
    ## Setup
    y   <- .setUp.y()
    S   <- .setUp.S()
    expos       <- matrix(390, nrow = nrow(y), ncol = 1)
    fdata.obj   <- fdata(y = y, S = S$V1, exp = expos)
    model.obj   <- model(K = 2)
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = FALSE, ranperm = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputbase", "check1")
    checkTrue(!mcmcout@ranperm, "check2")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    ## Set hier = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhier", "check3")
    checkTrue(!mcmcout@ranperm, "check4")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)
    ## Set hier = FALSE and storepost = TRUE
    prior.obj   <- prior(hier = FALSE)
    prior.obj   <- priordefine(fdata.obj, model.obj,
                               varargin = prior.obj)
    mcmc.obj    <- mcmc(storepost = TRUE, ranperm = FALSE)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputpost", "check5")
    checkTrue(!mcmcout@ranperm, "check6")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    ## Set hier = TRUE and storepost = TRUE
    prior.obj   <- priordefine(fdata.obj, model.obj)
    mcmcout     <- mixturemcmc(fdata.obj, model.obj,
                               prior.obj, mcmc.obj)
    checkTrue(class(mcmcout) == "mcmcoutputhierpost", "check7")
    checkTrue(!mcmcout@ranperm, "check8")
    checkEquals(NROW(mcmcout@par$lambda), mcmcout@M)
    checkEquals(NCOL(mcmcout@par$lambda), mcmcout@model@K)
    checkEquals(NROW(mcmcout@log$mixlik), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixlik), 1)
    checkEquals(NROW(mcmcout@log$mixprior), mcmcout@M)
    checkEquals(NCOL(mcmcout@log$mixprior), 1)
    checkEquals(NROW(mcmcout@weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@S), fdata.obj@N)
    checkEquals(NCOL(mcmcout@S), mcmc.obj@storeS)
    checkEquals(NROW(mcmcout@NK), mcmcout@M)
    checkEquals(NCOL(mcmcout@NK), mcmcout@model@K)
    checkEquals(NROW(mcmcout@clust), fdata.obj@N)
    checkEquals(NCOL(mcmcout@clust), 1)
    checkEquals(NROW(mcmcout@ST), mcmcout@M)
    checkEquals(NCOL(mcmcout@ST), 1)
    checkEquals(NROW(mcmcout@post$par$a), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$a), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$par$b), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$par$b), mcmcout@model@K)
    checkEquals(NROW(mcmcout@post$weight), mcmcout@M)
    checkEquals(NCOL(mcmcout@post$weight), mcmcout@model@K)
    checkEquals(NROW(mcmcout@hyper$b), mcmcout@M)    
    checkEquals(NCOL(mcmcout@hyper$b), 1)  
}



