# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

swap_cc <- function(values, index) {
    .Call(`_finmix_swap_cc`, values, index)
}

swap_3d_cc <- function(values, index) {
    .Call(`_finmix_swap_3d_cc`, values, index)
}

swapInteger_cc <- function(values, index) {
    .Call(`_finmix_swapInteger_cc`, values, index)
}

swapInd_cc <- function(values, index) {
    .Call(`_finmix_swapInd_cc`, values, index)
}

swapST_cc <- function(values, index) {
    .Call(`_finmix_swapST_cc`, values, index)
}

ldgamma_cc <- function(values, shape, rate) {
    .Call(`_finmix_ldgamma_cc`, values, shape, rate)
}

dgamma_cc <- function(values, shape, rate) {
    .Call(`_finmix_dgamma_cc`, values, shape, rate)
}

lddirichlet_cc <- function(values, par) {
    .Call(`_finmix_lddirichlet_cc`, values, par)
}

ddirichlet_cc <- function(values, par) {
    .Call(`_finmix_ddirichlet_cc`, values, par)
}

hungarian_cc <- function(cost) {
    .Call(`_finmix_hungarian_cc`, cost)
}

moments_cc <- function(classS4) {
    .Call(`_finmix_moments_cc`, classS4)
}

permmoments_cc <- function(classS4) {
    .Call(`_finmix_permmoments_cc`, classS4)
}

stephens1997a_poisson_cc <- function(values1, values2, pars, perm) {
    .Call(`_finmix_stephens1997a_poisson_cc`, values1, values2, pars, perm)
}

stephens1997a_binomial_cc <- function(values1, values2, pars, perm) {
    .Call(`_finmix_stephens1997a_binomial_cc`, values1, values2, pars, perm)
}

stephens1997b_poisson_cc <- function(values, comp_par, weight_par, max_iter = 200L) {
    .Call(`_finmix_stephens1997b_poisson_cc`, values, comp_par, weight_par, max_iter)
}

stephens1997b_binomial_cc <- function(values, reps, comp_par, weight_par) {
    .Call(`_finmix_stephens1997b_binomial_cc`, values, reps, comp_par, weight_par)
}

stephens1997b_exponential_cc <- function(values, comp_par, weight_par) {
    .Call(`_finmix_stephens1997b_exponential_cc`, values, comp_par, weight_par)
}

